import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from './layouts/navbar/Navbar'
import Footer from './layouts/footer/Footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ny hoaviko App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${montserrat.className} bg-[#050F1D] text-[#fefefe]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
